name: Rails Tests

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  RAILS_ENV: test
  NODE_VERSION: 22

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        # Set N number of parallel jobs you want to run
        # Remember to update ci_node_index below to 0..N-1
        ci_node_total: [1]
        # set N-1 indexes for parallel jobs
        # When you run 2 parallel jobs then first job will have index 0, the second job will have index 1 etc
        ci_node_index: [0]

    services:
      mongo:
        image: mongo:latest
        env:
          MONGO_INITDB_DATABASE: smart_tracking
        ports:
          - "27017:27017"

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Test Prep
        env:
          CI_NODE_INDEX: ${{ matrix.ci_node_index }}
        run: |
          bundle exec rake parallel:create["1"] parallel:load_schema["1"]

      - name: Run tests
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          CI_NODE_TOTAL: ${{ matrix.ci_node_total }}
          CI_NODE_INDEX: ${{ matrix.ci_node_index }}
        run : |
          bundle exec parallel_test spec/ -n $CI_NODE_TOTAL --only-group $CI_NODE_INDEX --type rspec
      - name: Add code coverage comment
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          lcov-file: ./coverage/lcov/smart-tracking-back.lcov
          github-token: ${{ secrets.GITHUB_TOKEN }}